Refactor for generic GIMP plug (#18)
* Refactor for generic GIMP plug

* Stage openvino-toolkit-2404 instead of content interface

* Adopt new GIMP generic interface design.

The generic content plug used by GIMP now only allows a plugin to
provide an addition to LD_LIBRARY_PATH using a
*.conf/add-ld-library-path file. This commits adds this file and patches
the plugin source to set environment variables from within the plugins,
since the GIMP snap maintainers do not want to manage custom environment
variables and shell commands for third-party plugins.

* Fix runtime environment for model-setup

* Remove git dependency.

The plugins run git describe in a subprocess to determine the
plugin version, which is very error prone inside the snap. This commit
runs the same git describe command from the snap build and then patches
the source code to return this value, so that the plugins no longer need
to run git commands from inside the snap.

* Add NPU libs to LD_LIBRARY_PATH

* Set LD_LIBRARY_PATH from plugin code.

The plugins contain newer versions of Intel graphics libs. The normal
mechanism for adding to LD_LIBRARY_PATH via a add-ld-library-path file
does not work in this scenario because it appends to the
LD_LIBRARY_PATH, resulting in some graphical libs being used from the
GIMP snap instead.

* Add wrapper scripts for plugins.

It turns out GIMP can run these shell scripts where I set the
environment for the plugins before calling the actual plugins. This is
much cleaner than patching the plugin source and also allows me to
prepend the LD_LIBRARY_PATH to ensure the plugins pick up the latest
Intel graphics libraries rather than the older versions from the
gpu-2404 content producer snap that is mounted inside the gimp snap.

* Add link to upstream docs

* Clarify patch and fix grammatical error

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -17,22 +17,24 @@ platforms:
 
 layout:
   /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
-    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl
-  /etc/gitconfig:
-    bind-file: $SNAP_DATA/etc/gitconfig
+    bind: $SNAP/openvino-gimp/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl
 
 package-repositories:
   - type: apt
     ppa: kobuk-team/intel-graphics
     key-id: 0C0E6AF955CE463C03FC51574D098D70AFBE5E1F
 
-# the recommended mountpoint for the content is /openvino-ai-plugins-gimp
 slots:
-  openvino-ai-plugins-gimp-libs:
+  gimp-plugins:
     interface: content
-    content: openvino-ai-plugins-gimp-2404
-    read:
-      - /
+    content: gimp-plugins
+    source:
+      read:
+        - $SNAP/semseg_ov
+        - $SNAP/stable_diffusion_ov
+        - $SNAP/superresolution_ov
+        - $SNAP/openvino_utils
+        - $SNAP/openvino-gimp
 
 plugs:
   intel-npu:
@@ -42,33 +44,21 @@ plugs:
     interface: content
     content: npu-libs-2404
     target: $SNAP/npu-libs
-  openvino-libs:
-    interface: content
-    content: openvino-libs-2404
-    target: $SNAP/openvino
-  dot-local-share-openvino-ai-plugins-gimp:
-    interface: personal-files
-    write:
-      - $HOME/.local/share/openvino-ai-plugins-gimp
 
 apps:
   model-setup:
-    command-chain: ["command-chain/openvino-launch", "command-chain/openvino-ai-plugins-gimp-launch"]
-    command: usr/bin/python3 $SNAP/model_setup.py
+    command: openvino-gimp/usr/bin/python3 $SNAP/openvino-gimp/model_setup.py
+    command-chain: [ command-chain/set-runtime-env ]
     plugs:
-      - dot-local-share-openvino-ai-plugins-gimp # models stored in home directory
       - opengl # Intel GPU access (device nodes)
       - intel-npu # Intel NPU access (device node)
       - npu-libs # Intel NPU access (libs)
       - network # for downloading models
-      - openvino-libs # OpenVINO runtime
     environment:
-      LD_LIBRARY_PATH: $SNAP/npu-libs:$LD_LIBRARY_PATH
-      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHONPATH
-      OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors
-      GIT_DIR: $SNAP/gimp-plugins/.git
-      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
-      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
+      PATH: $PATH:$SNAP/openvino-gimp/usr/bin:$SNAP/openvino-gimp/bin
+      LD_LIBRARY_PATH: $SNAP/openvino-gimp/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/npu-libs:$LD_LIBRARY_PATH
+      PYTHONPATH: $SNAP/openvino-gimp/lib/python3.12/site-packages:$SNAP/openvino-gimp/usr/lib/python3/dist-packages:$PYTHONPATH
+      OCL_ICD_VENDORS: $SNAP/openvino-gimp/etc/OpenCL/vendors
 
 parts:
   gimp-plugins:
@@ -86,18 +76,27 @@ parts:
       sed -i '/openvino/d' ./requirements.txt
       craftctl set version="$(git describe --tags --abbrev=4 --always)"
       git apply ${CRAFT_PROJECT_DIR}/patches/001-optimum-cli-from-path.patch
+      # This patch removes code from an installation utility that complicates snap packaging.
+      # The code is commented instead of removed for easier reference in future snap packaging
+      # and troubleshooting work.
+      git apply ${CRAFT_PROJECT_DIR}/patches/002-remove-git-dep-and-chmods.patch
+      # plug-ins rely on running git describe --tags at runtime to determine the
+      # plug-in version, which is not straightforward in a snap.
+      raw_version="$(git describe --tags)"
+      if [[ "$raw_version" =~ ^v?([0-9]+\.[0-9]+\.[0-9]+)(-([0-9]+)-g[0-9a-f]+)?$ ]]; then
+        version="${BASH_REMATCH[1]}"
+        sed -i -E "s/(return \")[0-9]+\.[0-9]+\.[0-9]+(\")/\1$version\2/" gimpopenvino/install_utils.py
+      else
+        echo "Could not build version string from raw_version: ${raw_version}"
+        exit 1
+      fi
     override-build: |
       craftctl default
-      mkdir -p ${CRAFT_PART_INSTALL}/weights ${CRAFT_PART_INSTALL}/gimp-plugins
+      mkdir -p ${CRAFT_PART_INSTALL}/weights
       cp -r weights/* ${CRAFT_PART_INSTALL}/weights/
       cp model_setup.py ${CRAFT_PART_INSTALL}
-      cp -r gimpopenvino/plugins/* ${CRAFT_PART_INSTALL}/gimp-plugins/
-      rm ${CRAFT_PART_INSTALL}/gimp-plugins/__init__.py
-      # plugins set plugin version from git tags, so copy repo metadata into snap
-      cp -r .git ${CRAFT_PART_INSTALL}/gimp-plugins/
-      chmod +x ${CRAFT_PART_INSTALL}/gimp-plugins/stable_diffusion_ov/stable_diffusion_ov.py
-      chmod +x ${CRAFT_PART_INSTALL}/gimp-plugins/semseg_ov/semseg_ov.py
-      chmod +x ${CRAFT_PART_INSTALL}/gimp-plugins/superresolution_ov/superresolution_ov.py
+      cp -r gimpopenvino/plugins/* ${CRAFT_PART_INSTALL}
+      rm ${CRAFT_PART_INSTALL}/__init__.py
     build-environment:
       - PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
     stage-packages:
@@ -112,7 +111,8 @@ parts:
       - libx11-6 # opencv-python dep
       - libxext6 # opencv-python dep
       - libgomp1 # pytorch dep
-      - git # plugin version displayed in GIMP by running "git describe"
+    stage-snaps:
+      - openvino-toolkit-2404/2025/stable
     stage:
       - -lib/python3.12/site-packages/torch/lib/libtorchbind_test.so
       - -usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
@@ -134,7 +134,16 @@ parts:
       - -usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
       - -usr/lib/x86_64-linux-gnu/libicui18n.so.74.2
     organize:
-      bin/optimum-cli: usr/bin/optimum-cli
+      bin: openvino-gimp/bin
+      etc: openvino-gimp/etc
+      include: openvino-gimp/include
+      lib: openvino-gimp/lib
+      lib64: openvino-gimp/lib64
+      model_setup.py: openvino-gimp/model_setup.py
+      share: openvino-gimp/share
+      usr: openvino-gimp/usr
+      var: openvino-gimp/var
+      weights: openvino-gimp/weights
 
   intel-graphics:
     plugin: nil
@@ -143,7 +152,7 @@ parts:
       # update paths to the Intel Installable Client Drivers (ICDs) for OpenCL
       intel_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel.icd
       intel_icd_so_path=$(cat ${intel_icd})
-      base_path="/snap/${SNAPCRAFT_PROJECT_NAME}/current"
+      base_path="/snap/${SNAPCRAFT_PROJECT_NAME}/current/openvino-gimp"
       echo "${base_path}""${intel_icd_so_path}" > "${intel_icd}"
       intel_legacy1_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel_legacy1.icd
       if [ -f ${intel_legacy1_icd} ]; then
@@ -165,20 +174,27 @@ parts:
       - libze-intel-gpu1
       - libigdgmm12
       - libigdgmm-dev
+    organize:
+      bin: openvino-gimp/bin
+      etc: openvino-gimp/etc
+      include: openvino-gimp/include
+      lib: openvino-gimp/usr/lib
+      share: openvino-gimp/share
+      usr: openvino-gimp/usr
 
-  command-chain-openvino:
-    plugin: dump
-    source-type: git
-    source: https://github.com/canonical/openvino-toolkit-snap.git
-    source-tag: 2025.2.0-amd64-rev30
-    stage:
-      - command-chain/openvino-launch
-
-  command-chain-openvino-ai-plugins-gimp:
+  command-chain:
     plugin: dump
     source: command-chain/
     organize:
-      '*': command-chain/
+      set-runtime-env: command-chain/set-runtime-env
+
+  plugin-wrappers:
+    plugin: dump
+    source: plugin-wrappers/
+    organize:
+      stable_diffusion_ov.sh: stable_diffusion_ov/stable_diffusion_ov.sh
+      semseg_ov.sh: semseg_ov/semseg_ov.sh
+      superresolution_ov.sh: superresolution_ov/superresolution_ov.sh
 
 lint:
   ignore:
@@ -187,13 +203,27 @@ lint:
       # by the linter because they are not
       # explicitly linked to any binary or
       # shared object
-      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbbind*
-      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbmalloc*
-      - openvino/usr/runtime/3rdparty/tbb/lib/libhwloc*
-      - usr/lib/x86_64-linux-gnu/libva.so.*
-      - usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.*
-      - usr/local/lib/libiga64.so*
-      - usr/local/lib/libigc.so.*
-      - usr/local/lib/libigdfcl.so.*
-      - usr/local/lib/libopencl-clang*
-      - lib/python3.12/site-packages/torch/lib/libtorch_global_deps.so
+      - openvino-gimp/lib/python3.12/site-packages/torch/*
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicuio.so.74.2
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicutest.so.74.2
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libiga64.so.2.16.0+0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libigc.so.2.16.0+0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libigdfcl.so.2.16.0+0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libva.so.2.2200.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.275
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libz3.so.4
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.1.6.34666
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_loader.so.1.23.1
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_tracing_layer.so.1.23.1
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_validation_layer.so.1.23.1
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicutu.so.74.2
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libopencl-clang.so.15
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
+      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicui18n.so.74.2
